package uk.ac.lincoln.a16629926students.community_anpr;

import java.util.ArrayList;

public class Crimes {
    public static String[] GetCrimeList(){
        String[] items = new String[]{
                "Murder",
                "Manslaughter",
                "Mayhem",
                "Common assault aka assault",
                "Battery",
                "Assault with intent to rob",
                "Assault with intent to rape",
                "Kidnapping / abduction",
                "Rape",
                "Buggery",
                "Arson",
                "Larceny",
                "Robbery",
                "Burglary",
                "Trespass",
                "Extortion",
                "Concealment of treasure trove",
                "Cheating",
                "Forgery",
                "High treason",
                "Petty treason",
                "Misprision of treason (disputed - alleged to be statutory)",
                "Misprision of felony (disputed - alleged not to exist)",
                "Compounding treason",
                "Sedition",
                "Seditious libel",
                "Contempt of the sovereign",
                "Espionage",
                "Contempt of court a.k.a. criminal contempt, contumacy",
                "Compounding a felony",
                "Fabrication of false evidence",
                "Escape from lawful custody",
                "Breach of prison/breaking prison",
                "Rescue/rescuing a prisoner in custody",
                "Harboring a fugitive or felon",
                "Effecting a public mischief (disputed - held to no longer exist)",
                "Malicious mischief",
                "Riot",
                "Mobbing",
                "Piracy",
                "Rout",
                "Affray",
                "Unlawful assembly",
                "Breach of the peace",
                "Defamatory libel",
                "Causing a public nuisance",
                "Obscene libel",
                "Blasphemy",
                "Blasphemous libel",
                "Incitement",
                "Challenging to fight Maintenance",
                "Champerty Embracery",
                "Eavesdropping",
                "Barratry, inciting litigation for profit",
                "Being a common scold",
                "Nightwalking (so as to cause alarm)",
                "Outraging public decency",
                "Forcible entry",
                "Forcible detainer",
                "Attempt Conspiracy",
                "Accessory",
                "Offering or paying a bribe",
                "Inebriation, public intoxication, posing a danger to others",
                "Running a disorderly house",
                "Administration of drugs with intent to enable or assist the commission of a crime",
                "Housebreaking with intent to steal",
                "Theft",
                "Use of threats with intent to extort money or property",
                "Wilful fireraising and culpable and reckless fireraising",
        };
        return items;
    }
}
